---
title: "sample code"
format: docx
---

## Introduction

Officially known as *A national longitudinal study of Muslim diversity and flourishing*, the Muslim Diversity Study (MDS) embraces a community-oriented approach by collaborating with the Muslim community in order to make decisions about the execution of data collection and for identifying key questions of interest for the community at large. It is important that such processes and decisions are recorded in the form of an article so that our findings and recommendations are shared with the broader public and future researchers in New Zealand and across the globe.

MDS started in 2023 as part of the New Zealand Attitudes and Values Study (NZAVS). The NZAVS is a planned 20-year-long longitudinal national probability annual panel study of social attitudes, personality, ideology and health outcomes that began in 2009 and is currently in its 16th year. It has so far collected data from more than 70,000 New Zealand residents using the electoral roll [@sibley2024]. The NZAVS has been instrumental in exploring key issues related to minorities, including but not limited to discrimination, intergroup relations, identity, distress, security, and the dynamics and mechanisms behind them.

The NZAVS has been uniquely positioned due to its prestigious reputation (over 300 peer-reviewed publications), longitudinal panel design, large sample size, and a large multi-disciplinary research team [@sibley2024]. More importantly, NZAVS has a nationally representative sample with data from different identity and religious groups [@sibley2024], thereby allowing researchers to compare data from different identity groups. However, the NZAVS has been undersampling Muslims by ten times lower than those of other religious groups [@sibley2024], which did not allow us to make meaningful inferences regarding Muslim lives and issues in comparison with other religious groups. Hence, the goal of MDS is to achieve as many as 650 Muslim respondents (i.e., \~ 1% of the total nation's Muslim community).

This article has three major parts. After providing the broader context of Muslims and MDS, we firstly discuss the process of co-designing and adjustments to the NZAVS design. Secondly, we present the final design and implemented protocol. Thirdly, we share the summary of advice and lessons learned in the process.


```{r}
#| label: tbl-ybocs-pclc
#| tbl-cap: YBOCS & PCLC Cut-Off Values
#| apa-note: The YBOCS ranges classify OCD severity, while PCLC ranges classify PTSD severity.


# Load necessary libraries
library(knitr)
library(tibble)

# Create the data frame
cut_off_values <- tibble(
  `YBOCS Range` = c("8 - 15", "16 - 23", "24 - 31", "32 - 40"),
  `OCD Severity` = c("Mild", "Moderate", "Severe", "Extreme"),
  `PCLC Range` = c("17 - 29", "28 - 29", "30 - 44", "45 - 85"),
  `PTSD Severity` = c(
    "No severity", 
    "Some symptoms", 
    "Moderate to moderately high", 
    "High severity"
  )
)

# Generate the table
cut_off_values %>%
  knitr::kable()

```


`echo` hides/shows the R code. This can be useful in at least three ways... let's think



abstract: "The New Zealand Attitudes and Values Study (NZAVS) is a national longitudinal study that aims to understand social values and attitudes in New Zealand residents by repeatedly tracking responses in the same people over time. Prior to the Muslim Diversity Study, the NZAVS has been considerably undersampling Muslims, with Muslim participation rates being ten times lower than those of other religious groups. The Muslim Diversity Study seeks to recruit a proportionately representative cohort of Muslim participants within the NZAVS to involve the Muslim community in longitudinal scientific research, and to convey results to Muslim community. Our hope is that by incorporating a broader range of Muslim experiences to the NZAVS, the stories of Muslim adversity and resilience will be more accurately recorded and understood. Such inclusion will enrich the scientific study of human flourishing, address the curiosity of the Muslim community in understanding its diversity, and contribute practical insights that can lead to the betterment of this marginalised community. Here, we describe the motivations for the Muslim Diversity Study, explain how we developed the study in consultation with the Muslim community, outline our methods for data collection, and offer practical guidelines for data collection from a culturally diverse religious community. In the first instance, this article offers a record of our research with Muslims in New Zealand. However, we hope this record will prove useful to investigators who seek to advance the scientific understanding of human flourishing in other settings through the national-scale longitudinal study of culturally diverse, marginalised religious communities."



## Method

Officially known as *A national longitudinal study of Muslim diversity and flourishing*, the Muslim Diversity Study (MDS) embraces a community-oriented approach by collaborating with the Muslim community in order to make decisions about the execution of data collection and for identifying key questions of interest for the community at large. It is important that such processes and decisions are recorded in the form of an article so that our findings and recommendations are shared with the broader public and future researchers in New Zealand and across the globe.

MDS started in 2023 as part of the New Zealand Attitudes and Values Study (NZAVS). The NZAVS is a planned 20-year-long longitudinal national probability annual panel study of social attitudes, personality, ideology and health outcomes that began in 2009 and is currently in its 16th year. It has so far collected data from more than 70,000 New Zealand residents using the electoral roll [@sibley2024]. The NZAVS has been instrumental in exploring key issues related to minorities, including but not limited to discrimination, intergroup relations, identity, distress, security, and the dynamics and mechanisms behind them.

The NZAVS has been uniquely positioned due to its prestigious reputation (over 300 peer-reviewed publications), longitudinal panel design, large sample size, and a large multi-disciplinary research team [@sibley2024]. More importantly, NZAVS has a nationally representative sample with data from different identity and religious groups [@sibley2024], thereby allowing researchers to compare data from different identity groups. However, the NZAVS has been undersampling Muslims by ten times lower than those of other religious groups [@sibley2024], which did not allow us to make meaningful inferences regarding Muslim lives and issues in comparison with other religious groups. Hence, the goal of MDS is to achieve as many as 650 Muslim respondents (i.e., \~ 1% of the total nation's Muslim community).

This article has three major parts. After providing the broader context of Muslims and MDS, we firstly discuss the process of co-designing and adjustments to the NZAVS design. Secondly, we present the final design and implemented protocol. Thirdly, we share the summary of advice and lessons learned in the process.